# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibo', '0006_point_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinvehicle',
            name='pt_in',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inpt', to='bibo.Point'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profileinvehicle',
            name='pt_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outpt', to='bibo.Point'),
        ),
    ]
