# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibo', '0007_auto_20160626_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
