# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibo', '0008_zone_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinvehicle',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
